Fix: ESLintで見つかった型エラーの修正
ishida-frontend/engineer-tenshoku-master pull request #204
Opened 2023-11-04 06:45 UTC by issiyda

## 概要

Fix: ESLintで見つかった型エラーの修正

## 実装理由・変更理由

既存エラーを解消しないとgithubactionでエラーが起きて今後テストなどができないため。
より良いコードにするため

## 特にレビューしてもらいたいこと

## 機能実行結果の動画

## 機能実行結果のスクショ

## UI変更前後のスクショ

## コメント

2023-11-04 08:08 UTC, Fumi369 commented
@issiyda 
手元でlintしてみたところ、まだ型エラーが残っているところがありますね。

残っているエラーを全部こちらにまとめました↓
https://shine-wall-83f.notion.site/ESLint-757306eec15a4643a6808378710ad263

型エラーはこちらです↓

```
Unexpected any. Specify a different type
```

2023-11-04 13:56 UTC, Fumi369 commented
`backend/scripts/readVideo.ts`が削除されてますが、これは使っているので再追加お願いします！

2023-11-04 13:58 UTC, Fumi369 requested changes
`backend/scripts/readVideo.ts`が削除されてますが、これは使っているので再追加お願いします！

2023-11-04 13:58 UTC, Fumi369 commented on frontend/components/organisms/CourseList.tsx
> +                            {courseTag.name}
`tag.`の削除で、タグが正常に表示されないようです。

![Screenshot 2023-11-04 at 22 23 52](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/72023616/81c673d3-3815-40c8-8f6e-2a49d3b368a3)

2023-11-05 00:56 UTC, issiyda commented on frontend/components/organisms/CourseList.tsx
> +                            {courseTag.name}
![スクリーンショット 2023-11-05 9 56 12](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/51443889/cfd5493a-c275-4683-a694-57f5f1634cf8)
修正しました！

2023-11-05 03:52 UTC, Fumi369 approved these changes
@issiyda 
LGTMです！

2023-11-05 03:52 UTC, Fumi369 commented
@issiyda 
LGTMです！

2023-11-05 03:57 UTC, merged