広告一覧表示(admin/advertisement)・広告編集画面(admin/advertisement/edit/[advertisementId])
ishida-frontend/engineer-tenshoku-master pull request #246
Opened 2024-02-20 14:34 UTC by preticure

## 概要

- 登録済の広告情報を一覧表示(admin/advertisement)
- 広告情報の編集

## 実装理由・変更理由
adminユーザーが広告一覧から編集ボタンをクリックするだけで個々の編集画面に移れるようにしました

## 特にレビューしてもらいたいこと

- 無駄な記述がないか

- 今は納期もあって出来なかったのですが、広告の数が多くなりそうだったら1ページにつき6個表示するみたいな感じでページング？機能と、広告一覧画面からCreate画面に飛べるようにしたいです

## 機能実行結果の動画
![localhost_3000_admin_advertisement - Google Chrome 2024-02-20 23-16-04](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/b5cacaba-075c-4539-9e38-e3eac1fded73)

## 機能実行結果のスクショ
![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/642c3cde-1828-4c09-9bcf-e8017cb427b6)

## UI変更前後のスクショ

## コメント
いつも即レスありがとうございます！
時間かかりすぎだと詰めてくだったので、程よく焦って取り組めました。
バックエンドの動きとTypeScriptも前よりわかるようになったので、次回deleteはもっと短い期間で仕上げられるように頑張ります。
いしださんに進捗詰められないように、随時共有するよう意識します！

2024-02-20 16:34 UTC, issiyda reviewed
@preticure 

確認お願いします！！

2024-02-20 16:34 UTC, issiyda commented on backend/application/advertisement.ts
> +      return advertisement
```suggestion
      const advertisements= await prisma.advertisement.findMany({
        where: {
          startFrom: {
            lte: new Date(), // 現在の日付以前の開始日時
          },
        },
      })
      return advertisements
```

実態と命名を揃えましょう！
findManyなので入ってくるのは配列で複数形の英語で示しましょう！

2024-02-20 16:34 UTC, issiyda commented on backend/application/advertisement.ts
> +      return updateAdvertisement
```suggestion
      const updatedAdvertisement = await prisma.advertisement.update({
        where: { id },
        data: {
          name,
          url,
          imageUrl,
          author,
          startFrom,
          endAt,
        },
      })
      return updatedAdvertisement
```

過去分詞の更新されたというのを示す
edをつけましょう！細いですが確認お願いします！

2024-02-20 16:34 UTC, issiyda commented on backend/controllers/advertisementController.ts
> +      )
```suggestion
      await this.advertisementApplicationService.createAdvertisement(
        advertisementData,
      )
```

serviceに直しておいて欲しいです！
→一つ前のPRで気づきませんでした。。。

2024-02-20 16:34 UTC, issiyda commented on backend/controllers/advertisementController.ts
> +      )
全体的に綴りは修正お願いします。

2024-02-20 16:34 UTC, issiyda commented on frontend/app/admin/advertisement/page.tsx
> +import React from "react";
これって消しても動きます？？

2024-02-20 16:34 UTC, issiyda commented on frontend/components/admin/pages/AdvertisementEditor.tsx
> +      }
```suggestion

    const { name, url, author, imageUrl, 残りも } = advertisementData

      const formData = {
        name,
        url,
        author,
        imageUrl,
        startFrom: startFrom.toISOString(),
        endAt: endAt.toISOString(),
      }
```

みたいに記述量減らせそうですね！

2024-02-20 16:34 UTC, issiyda commented on frontend/components/admin/pages/AdvertisementEditor.tsx
> +
```suggestion
```
上で書いてるのでいらないかと！

2024-02-20 16:34 UTC, issiyda commented on frontend/components/admin/pages/AdvertisementEditor.tsx
> +            endAt: advertisementData.endAt,
```suggestion
            id: advertisementData.id,
            name: advertisementData.name,
            url,
            imageUrl,
            author,
            startFrom,
            endAt
```

上のコメントの対応すれば省略できますね！

2024-02-20 16:34 UTC, issiyda commented on backend/startup.sh
> -yarn prisma generate
消さないでください🙏

2024-02-21 06:26 UTC, issiyda reviewed
@preticure 

確認お願いします！

2024-02-21 06:26 UTC, issiyda commented on backend/routes/router.ts
> +    advertisementController.updatedAdvertisement(req, res)
ここはというか自分が指摘した箇所以外のところはupdateAdvertisementで大丈夫です。

状態を的確に表したいです。

2024-02-21 06:26 UTC, issiyda commented on backend/controllers/advertisementController.ts
> +  async updatedAdvertisement(req: express.Request, res: express.Response) {
ここは
広告を更新するという意味を持つメソッドなので
updateAdvertisementで良いです。

updatedAdvertisement→広告を更新された
って意味になって意味がわからないですよね？

2024-02-21 06:26 UTC, issiyda commented on backend/application/advertisement.ts
> +  async updatedAdvertisement(params: {
ここも前のでOKです。

更新する
って意味なので

2024-02-21 06:26 UTC, issiyda commented on backend/application/advertisement.ts
> +      const updatedAdvertisement = await prisma.advertisement.update({
👍

2024-02-21 14:46 UTC, issiyda commented on frontend/components/admin/pages/AdvertisementEditor.tsx
> +            <FormLabel>終了</FormLabel>
```suggestion
            <FormLabel>終了日</FormLabel>
```

2024-02-21 14:48 UTC, issiyda commented on frontend/types/AdvertisementType.ts
> +export type AdvertisementType = {
同じ階層index.tsxがあるのでそこからexport するようにしておいてください！
中見れば何すれば良いか分かるはずです！

2024-02-21 14:48 UTC, issiyda commented on frontend/components/admin/pages/AdvertisementEditor.tsx
> +import { AdvertisementType } from '../../../types/AdvertisementType'
```suggestion
import { AdvertisementType } from '../../../types'
```

2024-02-21 14:50 UTC, issiyda commented on frontend/components/admin/pages/AdvertisementEditor.tsx
> +import { AdvertisementType } from '../../../types/AdvertisementType'
下のtypes/index.ts
からexport にしておいてくださいの対応でこういう風に書き直せるようになります。

複数型をimportする場合　indexからexport していなければ

import { AdvertisementType } from '../../../types/AdvertisementType'
import { TagType } from '../../../types'/TagType

みたいに行が増えますが indexからまとめてexport してると

import { AdvertisementType, TagType } from '../../../types'
って感じでまとめられます。

2024-02-22 00:29 UTC, issiyda reviewed
@preticure 

修正お願いします！

2024-02-22 00:29 UTC, issiyda commented on frontend/components/admin/pages/AdvertisementEditor.tsx
> +            })
```suggestion
            !!errors?.find((e) => {
              return e.path[0] === 'author'
            })
```

これでこれでエラー判定できませんか？
判定文が多いですね！

2024-02-22 00:29 UTC, issiyda commented on frontend/components/admin/pages/AdvertisementEditor.tsx
> +            })
他のバリデーション箇所も同様ですね！

2024-02-26 13:59 UTC, issiyda commented on backend/application/advertisement.ts
> +            lte: new Date(), // 現在の日付以前の開始日時
どこで使われる想定でしたっけ？
確認したいです！

2024-02-26 14:40 UTC, issiyda reviewed
@preticure

2024-02-26 14:40 UTC, issiyda commented on backend/application/advertisement.ts
> +            lte: new Date(), // 現在の日付以前の開始日時
@preticure 
deleted_atがnullかつ最新順でフロントに
advertisementの情報を返却する。

2024-02-29 13:48 UTC, issiyda requested changes
@preticure 
レビューしました〜

2024-02-29 13:48 UTC, issiyda commented on frontend/components/admin/pages/AdvertisementEditor.tsx
> +        {/* <FormControl
```suggestion
      このコードにしたほうがいい
```

2024-03-01 11:14 UTC, preticure commented on backend/application/advertisement.ts
> +        },
@issiyda 
開始日　昇順で取得するように変更しました
![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/2703dcb4-3a15-4103-8d5c-914ec26a5431)

2024-03-02 11:40 UTC, issiyda approved these changes
LGTMです！

2024-03-02 11:54 UTC, merged