Feature/tsk 472 frontend advertisement banner
ishida-frontend/engineer-tenshoku-master pull request #248
Opened 2024-02-24 12:47 UTC by preticure

2024-02-24 12:54 UTC, preticure commented on frontend/components/admin/organisms/AdvertisementTest.tsx
> +              <CloseButton position="absolute" top={2} right={2} />
@issiyda 
広告バナー
Closeボタンで広告閉じれるにしようと思ってます。
今はBoxクリックするとリンク先飛んでしまう仕様になっています。

2024-02-24 12:54 UTC, preticure commented on frontend/components/admin/organisms/AdvertisementTest.tsx
> +              <CloseButton position="absolute" top={2} right={2} />
![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/8996a1c2-570c-4349-b737-695ce6d1abd9)

2024-02-25 06:49 UTC, preticure commented on frontend/components/admin/organisms/AdvertisementTest.tsx
@issiyda 

https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/2fa032ee-4a06-4264-a502-249b71a9f984

×ボタンでコンポーネント非表示に
画像クリックでリンク先へ飛ぶ

2024-02-27 15:16 UTC, preticure commented
@issiyda 

**広告バナーをユーザー画面表示**

- 表示する広告が2件以上になっても画面崩れないこと確認してます。
- closeButtonも削除してバナー消せないようにしました

**確認動画**
https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/8784c0aa-e432-420d-8128-64cfb61a2944

**スクショ**
![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/bdbeb06d-2e82-4551-b7e6-829eb92c0e62)


**コメント**
親コンポーネントと子コンポーネント、今までちゃんと理解してなかったのでまた一つ成長できました！
知らなかったことに出会えるのがすごく楽しいです。
いつもありがとうございます！もっと色んなこと出来るようになりたいです。

2024-03-07 00:27 UTC, issiyda requested changes
@preticure 

確認お願いします！

2024-03-07 00:27 UTC, issiyda commented on backend/application/advertisement.ts
> +  async getBannerAd() {
```suggestion
  async getUserAdvertisments() {
```
にしましょうか！（ユーザ側の広告ですよね？？）
→取得してくるのはadvertismentのデータのはずなので

2024-03-07 00:27 UTC, issiyda commented on backend/controllers/advertisementController.ts
> +  async getBannerAd(req: express.Request, res: express.Response) {
ここも

2024-03-07 00:27 UTC, issiyda commented on backend/routes/router.ts
> +  advertisementController.getBannerAd(req, res)
ここも

2024-03-07 00:27 UTC, issiyda commented on frontend/components/atoms/AdvertisementBanner.tsx
> +  }
@preticure 
広告が一件もなかった時ってこのエラーが出る感じですかね？
→特段何も表示させなくていいかなと思ったのですがいかがでしょうか？

2024-03-09 10:30 UTC, preticure commented on frontend/components/admin/organisms/AdvertisementList.tsx
@issiyda 
![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/ee3a8bf5-6dc0-4999-8a3b-347f2ea88ffa)

2024-03-09 12:31 UTC, preticure commented on frontend/components/organisms/CourseDetailAccordionMenu.tsx
> +              session?.user.id,
@issiyda 
オプショナルチェーンないとエラー出るのでつけてます

2024-03-12 15:30 UTC, issiyda reviewed
@preticure 


確認お願いします！！

2024-03-12 15:30 UTC, issiyda commented on backend/application/advertisement.ts
> +      const BannerAd = await prisma.advertisement.findMany({
```suggestion
      const bannerAd = await prisma.advertisement.findMany({
```

冒頭は小文字にしましょう。
class名やType名、定数名は大文字でお願いします。

js tsのお作法なので覚えましょう。

2024-03-12 15:30 UTC, issiyda commented on backend/application/advertisement.ts
> +        `AdvertisementApplicationService: get advertisements error: ${error}`,
```suggestion
        `AdvertisementApplicationService: getUserAdvertisments error: ${error}`,
```

どの関数でエラーになったのか示したいので。

2024-03-12 15:30 UTC, issiyda commented on frontend/components/wrapper/pages/CourseList.tsx
> +  initialCourses: CourseListType[], advertisements: AdvertisementType[]
```suggestion
CourseListWrapperProps
```

みたいに定義して型を作りたいですね。

上のファイルの
```
type AdvertisementTypeProps = {
  advertisements: AdvertisementType[] | null | undefined
}
```
あたり参考にお願いします。

2024-03-13 07:40 UTC, issiyda approved these changes
@preticure 
LGTMです！

2024-03-13 07:40 UTC, merged