いいねボタンのカウント機能
ishida-frontend/engineer-tenshoku-master pull request #251
Opened 2024-02-29 11:33 UTC by suzury

## 概要
いいねボタンを押した際にカウントされカウントの数を表示させたい。
## 実装理由・変更理由
いいねボタンを押したら１いいねされて再度いいねボタン押したら１いいねのカウントは削除されるようにしたいです。
## 特にレビューしてもらいたいこと
フロントに表示できていないので間違えている箇所などがあれば教えていただきたいです。
## 機能実行結果の動画

## 機能実行結果のスクショ

## UI変更前後のスクショ

## コメント
レビューお願いします。

2024-02-29 12:06 UTC, suzury commented
**やりたいこと**
カウント数を取得して表示させたい。
**現状**
コンソールログ仕込んだところバックエンド側でエラーが出ております。（写真1枚目）
**やったこと**
調べたところGoodCountが存在しないとありましたので、
GoodVideoController.tsで問題があるのかと思いました。
いろいろなところにコンソールログ仕込んでもログでないのでどこが間違えているかわかりません。
記述に問題があるのでしょうか？間違えている箇所指摘していただきたいです。
<img width="783" alt="スクリーンショット 2024-02-29 21 02 50" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/c9699981-4faa-4971-b0dd-5f331bb803d2">

2024-02-29 12:07 UTC, suzury reviewed
@issiyda 
レビューお願いします。

2024-03-01 08:55 UTC, suzury commented
**やりたいこと**
カウント数が表示されない
**現状**
UIには問題なさそうですがフロント側で数字が表示されない。
デフォルト０スタートですが０も１も表示されません。
**やったこと**
カウントUIを調べたところやはり{goodCount}で表示できるようですが
表示できません。

コードに間違いがあるのでしょうか？
ご指摘お願いします。

2024-03-01 10:53 UTC, suzury reviewed
@issiyda 
確認お願いします。

2024-03-01 10:53 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
Cannot GET /goodVideo/655301cd-c0c6-4c89-9ef3-42ce995d64e2　とネットワークエラーが出ます。
goodVideoに対してのいいねを取得する感じではないのですか？
よくわからないです。

2024-03-01 12:42 UTC, suzury reviewed
@issiyda 
**やりたいこと**
先ほどと変わらずネットワークエラーが出るので解消したい。
**現状**
router.tsに記述しましたが先ほど質問したネットワークエラーは
解消されません。
**やったこと**
先ほどと変わらずなのでコードが間違っているか記述してないところがあるのかよくわかりません。

レビューでご指摘お願いします。

2024-03-01 12:46 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
追加したバックエンドのルーティングと
今ここで叩こうとしているURLって一致してますか？

確認お願いします。

```
goodVideoRouter.get('/:videoId/count', goodVideoController.getGoodCount)
```

と
```
          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
```

2024-03-01 12:53 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
/count いらないですよね　削除してみます
/:videoIdと/videoIdの：なしとありの意味はなんですか？

2024-03-01 12:55 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
getGoodCountではなくgoodVideoですか？

2024-03-01 12:57 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
> /:videoIdと/videoIdの：なしとありの意味はなんですか？


パスパラメータになります。
バックエンドの他のロジック参考にしてみてください。

:videoId
だとこのvideoIdのパラメータを使って何か操作をしているはずです。

2024-03-01 12:58 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
goodVideo/の部分ってDBのテーブルですよね？getGoodCountテーブルないのでgoodVideoですよね？

2024-03-01 12:58 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
> getGoodCountではなくgoodVideoですか？

goodVideoControllerの中を見て何か確認してください。

2024-03-01 15:32 UTC, suzury reviewed
@issiyda 
**やりたいこと**
countは流れているようですがエラーになります。
**現状**
写真添付のように一回押したらcount count... て流れていきクリックすると先ほどと同じエラーが表示されます。
**やったこと**
`${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}/count`,
に修正いたしました。
バックエンドによくわからないエラーが流れてきましたしたので調べたところよくあるエラーなので特定できないとのことで、？になりました。（写真二枚目）
<img width="519" alt="スクリーンショット 2024-03-02 0 25 52" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/d3e28534-9891-4c97-9232-7aa8f7923e31">
<img width="812" alt="スクリーンショット 2024-03-02 0 17 06" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/16888a2a-558a-4b41-bf2d-d73751ae4490">

2024-03-01 15:32 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +    const [goodCount, setGoodCount] = useState(0)
このgoodCountは消してコミットしてプッシュしたはずなのにこっちでは消されていないのはなぜですか？

2024-03-01 15:32 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
ここに/count 入れてコミットしてプッシュしたはずなのですがこっちでは反映されてないのはなぜですか？

2024-03-01 16:05 UTC, issiyda commented on backend/application/goodVideo.ts
> +    console.log('Error', Error)
@suzury 

この
Error
が宣言されていないのに呼び出されてるのが問題じゃないですかね？

2024-03-02 08:37 UTC, suzury reviewed
@issiyda 
**やりたいこと**
エラーを解消したい
**現状**
goodCountのカラムがないとエラーで言われます
**やったこと**
この前カラムは今回の実装で必要ないとおっしゃっていたので
作成してないですが、呼び出さなくてもいいコードに編集するべきってことですか？
よくわかりません。
レビューお願いします。
**スクリーンショット**
<img width="858" alt="スクリーンショット 2024-03-02 17 31 29" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/81f0803c-7664-4c80-a9d2-7d8c182abaaf">

2024-03-02 08:37 UTC, suzury commented on backend/controllers/goodVideoController.ts
> +      console.error('getGoodCount エラー:', error)
ここにログを仕込んだところ、goodCountのカラムがないと言われたのですが、
今回の実装は必要ないんですよね？
このエラーはどうやったら消えますか？
<img width="858" alt="スクリーンショット 2024-03-02 17 31 29" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/6fb3a08d-5dbf-4aa0-8180-8306c8a0fb74">

2024-03-02 10:00 UTC, suzury reviewed
@issiyda 
**質問**
カウントは流れているように見えますが
一度いいねボタン押したら１いいね付与機能のはずですが
１いいね押したら一度に６個countログが流れてきます。
確認お願いします。
**スクリーンショット**
<img width="521" alt="スクリーンショット 2024-03-02 18 52 06" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/14dde3d4-d8bc-483b-a8db-c53529b25bde">

2024-03-02 10:04 UTC, issiyda commented on backend/application/goodVideo.ts
> +    const existingGoodVideo = await prisma.goodVideo.count({
本当はよくないですが一旦大丈夫です！
そしてconstで示した値existingGoodVideoを
goodCountに戻してもらっていいですか。

実態と同じにしてください。
await prisma.goodVideo.countの結果って
goodVIdeoの数ですよね？？

existingGoodVideoはGoodVideoの存在
goodCountはgoodの数

って意味になるのでどの用語が適しているかを常に考えてください。
このコードを見るのはすずさんだけじゃないんで。すずさんが適当に名前つけちゃうと他の人がこのコード見た時によくわからなくなってしまうので気をつけましょう！

2024-03-02 10:17 UTC, suzury commented on backend/application/goodVideo.ts
> +    const existingGoodVideo = await prisma.goodVideo.count({
承知しました。修正いたしました。

2024-03-05 09:58 UTC, suzury reviewed
@issiyda 
**やりたいこと**
カウントをフロント表示させたい
**現状**
カウントがフロントに表示されません。
**やったこと**
調べたところGoodButton.tsxコード内で{goodCount}で表示できるみたいですが
記述してあるのに表示できていません。
chakraUIのスタイルのスペースの問題なのかコードの問題なのかわかりません。

レビューお願いします。

2024-03-07 14:46 UTC, suzury reviewed
@issiyda 
**やりたいこと**
アイコンを使用したいがエラーが出ます
**現状**
```
 <Button
      onClick={(e) => {
        handleLike(e)
      }}
      icon={isLiked ? <Icon as={FaRegThumbsUp} /> : <Icon as={FaThumbsUp} />}
```
ここにiconは使用できませんとエラーが出ます。
**やったこと**
WatchedButton.tsxの実装を参考にIconButtonではなくButtonで実装しました。
アイコンを使用するには<IconButton/>ではないといけないみたいですが、
<Button/>で実装するなら他にアイコンを設定する方法があるのでしょうか？
調べて探したのですが見つかりません。

レビューお願いします。

2024-03-07 14:46 UTC, suzury commented on frontend/components/atoms/GoodButton.tsx
>        icon={isLiked ? <Icon as={FaRegThumbsUp} /> : <Icon as={FaThumbsUp} />}
ここにiconは使用できませんとエラーが出ます。

2024-03-08 13:33 UTC, suzury reviewed
@issiyda 
**やりたいこと**
いいねボタン押してもカウント表示が１にならない
**現状**
写真添付の通りいいねボタン押してもカウントが０のままです。
カウントは流れています。
**やったこと**
試しにUIを視聴済みボタンと同じに揃えてみました。
**スクリーンショット**
<img width="1397" alt="スクリーンショット 2024-03-08 22 27 52" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/aa9260cd-06e6-48aa-9ca2-8d56125428aa">

2024-03-08 13:36 UTC, suzury reviewed
レビューよろしくお願いします

2024-03-08 13:36 UTC, suzury commented on frontend/components/atoms/GoodButton.tsx
> +import { Button, HStack, Icon } from '@chakra-ui/react'
`import { Button, HStack, Icon } from '@chakra-ui/react'`
Iconは削除するの忘れていたので、削除しておきます。

2024-03-08 23:02 UTC, suzury reviewed
@issiyda 
**やりたいこと**
カウントを表示させたい
**現状**
カウントが０のままです。
**やったこと**
他の実装を参考にrouter.refresh()記述してみました。
カウントの下に置いてますが
合っているか確認していただきたいです。

2024-03-08 23:22 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        router.refresh()
```suggestion
        setIsLiked(!isLiked)
        setGoodCount(!isLiked ? goodCount + 1 : goodCount - 1)
```

状態に合わせて変えてもらいたいんですがリアルタイムでいいねを表示させなくてもいいのでお願いします。

2024-03-09 11:14 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        router.refresh()
リアルタイムでいいねを表示させずにUIを変える形でというのはどういうことですか？

2024-03-09 11:30 UTC, suzury reviewed
@issiyda 
**やりたいこと**
` goodCount={0}
   goodCount={goodCount}`
の0からgoodCountに変更した際のエラー文を解消したい。
**現状**
名前goodCountがありませんとエラー表示されます。
**やったこと**
0ではなくgoodCountを表示したいので指摘された箇所を
goodCount{goodCount}に変更してみました。
あと、指摘された箇所に
コンソールログを仕込んだのですがログが出なく何も表示されません。
PRでそのコード部分にコメント残しました。

2024-03-09 11:30 UTC, suzury commented on frontend/components/pages/CourseDetail.tsx
> +            goodCount={goodCount}
` goodCount={0}
   goodCount={goodCount}
`
0ではなく{goodCount}にしたら名前goodCountが見つかりませんとエラー文が表示されます。

2024-03-09 11:30 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        console.log('data:', data)
このログは何も表示されませんでした。

2024-03-09 11:30 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
>  }) {
レンダリングされているかここの下にコンソールログを仕込んでも何も表示されませんでした。

2024-03-09 12:23 UTC, suzury reviewed
ネットワークのログには
count0からcount1に表示されるようになりました。
<img width="455" alt="スクリーンショット 2024-03-09 21 19 48" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/067c13f7-ae43-41b4-bad2-9f40b8dd4d04">

2024-03-09 12:55 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        router.refresh()
ボタン押すたびに都度goodCountをバックエンド側に取得しにいかないってことです。

2024-03-09 12:57 UTC, issiyda commented on frontend/components/pages/CourseDetail.tsx
> +            goodCount={goodCount}
@suzury 
export function CourseDetail({

の箇所で
goodCountを受け取るように実装してないからです。

2024-03-09 15:01 UTC, suzury reviewed
@issiyda 
**やりたいこと**
リアルタイムで取得せずカウント機能のUIを変えるというのは
UIだけカウントを表示させなくていいってことですか？
理解力なくてすみません
**現状**
一旦カウント表示のUI消しました。
**やったこと**
カウントのUIを消すって意味なのかと思って
GoobButton.tsxの{goodCount}一旦消してます。
**スクリーンショット**
<img width="455" alt="スクリーンショット 2024-03-09 23 49 16" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/249d85b6-6213-4cf5-af1c-03288465a5b6">
<img width="455" alt="スクリーンショット 2024-03-09 23 52 09" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/a2a6037c-b725-474b-ab00-d3c61cd6890a">

2024-03-10 09:49 UTC, suzury reviewed
@issiyda 
**やりたいこと**
0すら表示されなくなったので解消したい
**現状**
コードを戻しただけなのになぜか０すら表示されなくなりました。
**やったこと**
カウントのAPI通信をせずに表示させるとのことだったので色々コードを書いたり消したりfetchから下をコメントアウトしたり色々してたらよくわからなくなったので
元のコードに戻しました。そしたら０が表示されなくなりました。
コメントアウトしてみた部分
```
await fetch(
          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              userId,
              videoId,
            }),
          },
        )

```

2024-03-10 09:49 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
>          )
`await fetch(
          `${process.env.NEXT_PUBLIC_BACKEND_URL}/goodVideo/${videoId}`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              userId,
              videoId,
            }),
          },
        )`

ここをコメントアウトしたらAPI通信せずに表示できるのではと思い
コメントアウトしたり色々してたらよくわからなくなってきたので
元に戻したら０が表示されなくなりました。ネットワークではカウントは取れてます。

2024-03-11 00:57 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +    fetchGoodCount()
@suzury 
useEffect使って
    fetchGoodCount()
呼び出してもらっていいですか？
第二引数 [ ]

にすれば一度しか呼び出されないようにできるので

2024-03-11 01:12 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        const data = await res.json()
dataに何入ってきてるか調べてもらっていいですか？

2024-03-11 14:49 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        const data = await res.json()
いいね押したらdataに「１」が入ってきてます。
↓
<img width="1074" alt="スクリーンショット 2024-03-11 23 48 21" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/47c78565-af94-47c9-9208-3b942f877f77">

2024-03-11 15:11 UTC, suzury reviewed
@issiyda 
**やりたいこと**
カウント数を数字にしたい。
**現状**
ボタン初期表示undefind,ボタン押したらNaNと表示されます。
**やったこと**
・useEffectで初回のみ実行される処理に修正しました。
・{goodCount}のままだと０すら表示されないので、<Text></Text>囲った。
文字列しかだめと言われるのでgoodCountを文字列として渡す
<Text>{String(goodCount)}</Text> 
にしたらいいねボタンが初期表示undefind,押したらNaNと表示される。
・fetchGoodCountをuseEffectに修正して指摘されたdata部分をログ置いて調べた結果は、
「data 1」でした。
**スクリーンショット**
<img width="1074" alt="スクリーンショット 2024-03-11 23 48 21" src="https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/067b1248-dbee-4b6a-92d8-c5a27add7d71">

2024-03-11 15:11 UTC, suzury commented on frontend/components/atoms/GoodButton.tsx
> +        {goodCount}
この{goodCount}を<Text></Text>で囲うと文字列しかだめと言われるのでgoodCountを文字列として渡す
`<Text>{String(goodCount)}</Text>
`
にしたらundefindが初期表示され、いいねを押すとNaNになりました。

2024-03-11 15:11 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +    const [goodCount, setGoodCount] = useState(0)
いいねボタンのカウント数がundefindやNaNになるのは調べたところ
ここで０を設定していないから。らしいのですが
ここで０に設定しています。
API側がおかしいのでしょうか？

2024-03-11 15:11 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          const data = await res.json()
ここにコンソールログ置いたらdata 1 と表示されました。

2024-03-11 15:26 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        const data = await res.json()
@suzury 
じゃあ何しないといけないか考えて
実装してください。

2024-03-12 12:45 UTC, suzury reviewed
@issiyda 
修正しました。二箇所にコメントしてあります。
カウントフロント表示できました。
UIも視聴済みボタンと揃えました。

https://github.com/ishida-frontend/engineer-tenshoku-master/assets/150606468/78c9fdef-81ca-4b73-90de-6fe1e00a0128


動画添付しておきます。
確認お願いします。

2024-03-12 12:45 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        setGoodCount(data)
dataのみにコード修正しました。

2024-03-12 12:45 UTC, suzury commented on frontend/components/atoms/GoodButton.tsx
> +        <Text>{goodCount}</Text>
UIを視聴済みボタンと揃えるよう修正しました。

2024-03-12 13:49 UTC, issiyda requested changes
@suzury 
確認お願いします！！

2024-03-12 13:49 UTC, issiyda commented on backend/application/goodVideo.ts
> +    //deleted_at が null のいいねのみをカウントする
コメントは基本見ればわかるものは削除でお願いします。
→これくらいのコメントはコード見たらわかるようにして欲しいです。

2024-03-12 13:49 UTC, issiyda commented on backend/controllers/goodVideoController.ts
> +      res.status(500).json({ message: 'カウントエラーが発生しました' })
カウントエラーってどういう意味でしょう？？

自分だったら
ビデオのいいね数取得でエラーが発生しました
にします。伝わらない言葉を使うのはやめましょう。

2024-03-12 13:49 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +  const router = useRouter()
router

って使ってます？

2024-03-12 13:49 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        fetchGoodCount()
2行消しても動くと思うんですがどうでしょうか？

2024-03-12 13:49 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +    fetchGoodCount()
@suzury 
これって結局戻しちゃった感じですか？
useEffect使って一度だけ呼び出す形に書き直して欲しいです。

2024-03-12 15:08 UTC, suzury commented on backend/application/goodVideo.ts
> +    //deleted_at が null のいいねのみをカウントする
わかりました。削除しました。

2024-03-12 15:09 UTC, suzury commented on backend/controllers/goodVideoController.ts
> +      res.status(500).json({ message: 'カウントエラーが発生しました' })
修正しました。

2024-03-12 15:09 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +  const router = useRouter()
router使う話でしたので記述しました。削除しました。

2024-03-12 15:09 UTC, suzury commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        fetchGoodCount()
削除しました。

2024-03-12 15:15 UTC, suzury reviewed
@issiyda 
コメント箇所修正しました。
useEffectの件ですが、カウント機能着手する際に私が質問にて
useEffect使用しようとしていることを伝えたら
今回のカウント数はuseEffectは使用しない対応です。との回答だったので
最終的には使用しないのかと思っていました。
useEffectに修正しました。

2024-03-17 17:46 UTC, merged