TSK-485 section進捗率保存できる機能
ishida-frontend/engineer-tenshoku-master pull request #254
Opened 2024-03-04 15:14 UTC by preticure

## 概要

## 実装理由・変更理由

## 特にレビューしてもらいたいこと

## 機能実行結果の動画

## 機能実行結果のスクショ

## UI変更前後のスクショ

## コメント

2024-03-04 15:16 UTC, preticure commented on frontend/components/wrapper/pages/CourseDetail.tsx
@issiyda 

![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/a9197e66-78a7-4b9c-8488-5c0dcda416db)

2024-03-07 13:13 UTC, preticure reviewed
@issiyda 
## 概要
セクションの進捗率を計算して表示する

## 実装理由・変更理由
コース全体の進捗率はあって、個々のセクションの進捗率はなかったから。

## 特にレビューしてもらいたいこと


## 機能実行結果の動画

https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/9b60a8b7-87b2-4165-8cda-98429a87258c



## 機能実行結果のスクショ
スクショ取るの忘れてしまいました。
seedも戻してしまったので今回は許していただけないでしょうか。すみません

## UI変更前後のスクショ

## コメント
遅くなってすみません。まだ、オブジェクトあまり理解できていないのですが、めげずに頑張ります。レビューおねがいします

2024-03-08 00:11 UTC, issiyda requested changes
@preticure 

確認お願いします！

2024-03-08 00:11 UTC, issiyda commented on frontend/components/organisms/CourseDetailAccordionMenu.tsx
> +              session?.user?.id,
```suggestion
              session.user.id,
```

上で
```  
    {session?.user?.id && (
```
の判定をしているので変更しても型のエラーは起きないはずです。

2024-03-08 00:11 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +      useState(0)
これって何に使ってます？

2024-03-08 00:11 UTC, issiyda commented on frontend/components/atoms/SectionProgressBar.tsx
> +export const SectionProgressBar = ({
barじゃないと思うんで(ただ%を出してるだけ)コンポーネントの名前変えてください！

sectionの進捗率

を示す名前あたりで考えてもらえると。
慣れて欲しいのですが
あいみさんは%のテキスト認識していても、他の人がこのコンポーネント名を見るとbarをイメージしてしまいます。実態をいかに適切に示せるか。これを意識してください。


あとこれくらいだったらコンポーネントにしなくても良いのでそのままorganismsに書いてもらっていいですか？
共通で使うイメージが今のところ湧かないですね！

2024-03-08 00:11 UTC, issiyda commented on frontend/components/organisms/CourseDetailAccordionMenu.tsx
> +    const totalVideos = section.videos.length
```suggestion
    const totalVideoCount = section.videos.length
```

2024-03-08 23:34 UTC, issiyda approved these changes
LGTMです！

2024-03-09 03:51 UTC, merged