[WIP]コース詳細画面の渡すパラメータが多すぎる問題の修正
ishida-frontend/engineer-tenshoku-master pull request #256
Opened 2024-03-08 10:53 UTC by Fumi369

## 概要

## 実装理由・変更理由

## 特にレビューしてもらいたいこと

## 機能実行結果の動画

## 機能実行結果のスクショ

## UI変更前後のスクショ

## コメント

2024-03-09 01:08 UTC, issiyda requested changes
@Fumi369 
railsの書き方になれてしまったのかなぁと思うのですが
jsのお作法でコメント色々しておきました！

2024-03-09 01:08 UTC, issiyda commented on frontend/app/course/[courseId]/[videoId]/page.tsx
> +    let WrapperProps = {
```suggestion
    const wrapperProps = {
```

再代入しない値はconstで行きましょう！
後冒頭は小文字で。

2024-03-09 01:08 UTC, issiyda commented on frontend/types/CourseDetailType.ts
> +import { Session } from 'next-auth'
typesの型を外出ししてもらったと思うんですが再度使うイメージがわかないので使うファイルに記述してもらって大丈夫です！！

2024-03-09 01:08 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +    let courseDetailProps = {
```suggestion
    const courseDetailProps = {
```

2024-03-09 01:08 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +export function CourseDetailWrapper(WrapperProps: WrapperPropsType) {
```suggestion
export function CourseDetailWrapper(CourseDetailProps: CourseDetailPropsType) {
```

このコンポーネントへのpropsなので
こういう命名を多くの現場ではしてますね！

2024-03-09 01:08 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +  const videoId = WrapperProps.videoId
```suggestion
  const {userId , videoId } = WrapperProps
```

これなら1行でかけます！

2024-03-09 01:08 UTC, issiyda commented on frontend/components/pages/CourseDetail.tsx
> +            user_id: courseDetailProps.session.user.id,
下だとsessionの後に
?
がついていないんですがどっちが正しいでしょうか？

2024-03-09 01:08 UTC, issiyda commented on frontend/components/pages/CourseDetail.tsx
> +  let accordionMenuProps = {
const { session,completePercentage, checkedStatus ...その他も同様に} = courseDetailProps

ってしてあげるとこの下で
courseDetailPropsを何度も書かなくて良さそうですね。

2024-03-09 04:01 UTC, Fumi369 commented on frontend/app/course/[courseId]/[videoId]/page.tsx
> +    let WrapperProps = {
こちらと他の該当箇所も修正しました！

2024-03-09 04:12 UTC, Fumi369 commented on frontend/types/CourseDetailType.ts
> +import { Session } from 'next-auth'
型定義をコンポーネントファイルに戻しまして、`CourseDetailType.ts` を削除しました！
型定義を別のファイルからインポートすることで、コンポーネントファイルのコード量を減らせると思いやってみたのですが、型の再利用性が重要なんですね。

2024-03-09 04:12 UTC, Fumi369 commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +    let courseDetailProps = {
修正しました！

2024-03-09 04:20 UTC, Fumi369 commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +export function CourseDetailWrapper(WrapperProps: WrapperPropsType) {
現場のやり方、勉強になります！
`courseDetailProps` という名前は、別コンポーネント（`frontend/components/pages/CourseDetail.tsx`）で既に使用しているので、`courseDetailWrapperProps` としてみました。

2024-03-09 04:22 UTC, Fumi369 commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +  const videoId = WrapperProps.videoId
修正しました。ありがとうございます！

2024-03-09 05:51 UTC, Fumi369 commented on frontend/components/pages/CourseDetail.tsx
> +            user_id: courseDetailProps.session.user.id,
だいさんが書いたコードなので、それに対しての意見になりますが、「?」がないのが正しいと思います。
このコードが含まれる `createQuestion` は質問作成の関数ですね。
現状では、未ログインでは質問フォームすら表示されない仕様のようなので、質問を POST 送信する時点でログインしていないことはおかしく、ここで `session`が null であることはないかなと思います。
なので、ここに「?」は不要だと思います。

また、いしださんの言う下（createAnswer）の `session` についても、回答作成にはログインしている必要があるようなので「?」は不要かと思います。

2024-03-09 06:34 UTC, Fumi369 commented on frontend/components/pages/CourseDetail.tsx
> +  let accordionMenuProps = {
修正しました！

2024-03-12 15:40 UTC, issiyda reviewed
@Fumi369

2024-03-12 15:40 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +                viewingStatus.user_id === courseDetailWrapperProps.userId,
```suggestion
                viewingStatus.user_id === userId,
```

2024-03-12 15:40 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        [courseDetailWrapperProps.videoId]: newWatchedStatus,
```suggestion
        [videoId]: newWatchedStatus,
```

2024-03-12 15:40 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          [courseDetailWrapperProps.videoId]: newWatchedStatus,
```suggestion
          [videoId]: newWatchedStatus,
```

2024-03-12 15:40 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        [courseDetailWrapperProps.videoId]: newFavoritedStatus,
```suggestion
        [videoId]: newFavoritedStatus,
```

2024-03-12 15:40 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +            userId: courseDetailProps.session?.user?.id,
```suggestion
            userId,
```
でいけそうですかね？

2024-03-14 12:25 UTC, Fumi369 commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +                viewingStatus.user_id === courseDetailWrapperProps.userId,
修正しました！

2024-03-14 12:26 UTC, Fumi369 commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        [courseDetailWrapperProps.videoId]: newWatchedStatus,
修正しました！

2024-03-14 12:26 UTC, Fumi369 commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +          [courseDetailWrapperProps.videoId]: newWatchedStatus,
修正しました！

2024-03-14 12:27 UTC, Fumi369 commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +        [courseDetailWrapperProps.videoId]: newFavoritedStatus,
修正しました！

2024-03-14 12:32 UTC, Fumi369 commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +            userId: courseDetailProps.session?.user?.id,
いけました！

2024-03-14 12:51 UTC, Fumi369 commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +  } = courseDetailWrapperProps
@issiyda 
このコンポーネントで使うプロパティだけを分割代入で取り出して、`courseDetailWrapperProps.xxx`の形でプロパティを取得している箇所を全てなくしてみました。

2024-03-14 23:58 UTC, issiyda reviewed
@Fumi369 

コンポーネントに渡す値がごちゃごちゃ書いてあるより今の書き方の方がスッキリして何を渡すのか見通しが非常にしやすくなりました！

LGTMです！

2024-03-14 23:58 UTC, issiyda commented on frontend/components/wrapper/pages/CourseDetail.tsx
> +  } = courseDetailWrapperProps
これはやった方が良さそうだったのでNiceです！

2024-03-15 00:40 UTC, issiyda approved these changes

2024-03-15 00:54 UTC, merged