【WIP】deleted_atに値のあるタグが表示されないようにする
ishida-frontend/engineer-tenshoku-master pull request #259
Opened 2024-03-10 01:49 UTC by Fumi369

## 概要

## 実装理由・変更理由

## 特にレビューしてもらいたいこと

## 機能実行結果の動画

## 機能実行結果のスクショ

## UI変更前後のスクショ

## コメント

2024-03-21 12:09 UTC, issiyda reviewed
@Fumi369 

確認お願いします！！

2024-03-21 12:09 UTC, issiyda commented on frontend/components/admin/atoms/DeleteButton.tsx
> +'use client'
これはatom単位に書くものではないのでやめたいですね！！

2024-03-21 12:09 UTC, issiyda commented on frontend/components/admin/atoms/DeleteButton.tsx
> +  }
もし何度もここの記述書きたくなかったら
hooks（関数として）切り出すなどしたいですね。

2024-03-21 12:09 UTC, issiyda commented on frontend/components/admin/atoms/DeleteButton.tsx
> +      </Modal>
buttonってfile名になっているのに
Modalが入っているのは自分はやはり違和感ありますね！

modalはmodalだけでatomsとして用意したいです。

2024-03-21 12:09 UTC, issiyda commented on backend/__tests__/medium/application-services/tag.test.ts
> +import crypto from 'crypto'
ふみさんにもお伝えしておくと
今のこのテスト達意味がないテストになっています。

返却値をmockにしてそれと値を比較しても
そりゃそうだろ
ってテストになってるので。。。

2024-03-24 13:11 UTC, Fumi369 commented on backend/prisma/migrations/20240323142001_add_deleted_at_to_question/migration.sql
> +ALTER TABLE `Question` ADD COLUMN `deleted_at` DATETIME(3) NULL;
このカラムの追加理由は以下のとおりです。

先日の Prisma Client extension の追加により、findMany() が自動で deleted_at カラムの情報を参照するようになりました。
しかし、Question テーブルには deleted_at カラムがないため、findMany() で質問を取得するロジックでエラーが発生しました。
そのエラー解消のために、同カラムを追加しました。

2024-03-24 13:14 UTC, Fumi369 commented on frontend/components/admin/atoms/DeleteButton.tsx
> +'use client'
削除しました！

2024-03-24 13:15 UTC, Fumi369 commented on frontend/components/admin/atoms/DeleteButton.tsx
> +  }
`frontend/hooks/useDeleteItem.ts` 関数として切り出してみました！

2024-03-24 13:16 UTC, Fumi369 commented on frontend/components/admin/atoms/DeleteButton.tsx
> +      </Modal>
`frontend/components/admin/atoms/DeleteConfirmModal.tsx` として atoms コンポーネントに切り出しました！

2024-03-24 13:22 UTC, Fumi369 commented on backend/__tests__/medium/application-services/tag.test.ts
> +import crypto from 'crypto'
@issiyda 
なるほど、それはそうですね…。
そういうことであれば、 @preticure さんが [tag のテストを実装中](https://github.com/ishida-frontend/engineer-tenshoku-master/pull/268)でもあるので、このテストは削除してしまったほうがいいでしょうか？

2024-03-24 14:06 UTC, issiyda commented on backend/__tests__/medium/application-services/tag.test.ts
> +import crypto from 'crypto'
@Fumi369 
削除しましょうか！！

2024-03-24 14:12 UTC, issiyda commented on frontend/hooks/useDeleteItem.ts
> +  const deleteItem = async ({ id, itemToDelete }) => {
```suggestion
  const deleteItem = async ({ id, deleteTarget }: {
  id: string , deleteTarget: string) => {
```

みたいな方がいいかなと思いました。

itemToDelete
→抽象度が高い気がしました！

2024-03-24 22:19 UTC, Fumi369 commented on frontend/hooks/useDeleteItem.ts
> +  const deleteItem = async ({ id, itemToDelete }) => {
該当箇所全て、`deleteTarget` へ変更しました！

2024-03-27 23:37 UTC, issiyda requested changes
Buttonの内容だけ
1点だけ修正お願いします！

2024-03-27 23:37 UTC, issiyda commented on frontend/components/admin/atoms/DeleteConfirmModal.tsx
> +  }
atomsの中でhooksを使うのはやめましょう。
あくまでatomsはUI表示のためのものなので。

必ずメソッドは親から受け取るようにお願いします。
```suggestion
```

2024-03-27 23:37 UTC, issiyda commented on frontend/components/admin/atoms/DeleteConfirmModal.tsx
> +  onClose: () => void
```suggestion
  id,
  deleteTarget,
  isOpen,
  onClose,
  onClick
}: {
  id: string
  isOpen: boolean
  onClose: () => void
  onClick: () => void
```

2024-03-27 23:37 UTC, issiyda commented on frontend/components/admin/atoms/DeleteConfirmModal.tsx
> +          <Button variant="ghost" onClick={onClose}>
```suggestion
          <Button variant="ghost" onClick={onClick}>
```

2024-03-27 23:37 UTC, issiyda commented on frontend/hooks/useDeleteItem.ts
> +export const useDeleteItem = () => {
👍

2024-03-28 12:33 UTC, Fumi369 commented on frontend/components/admin/atoms/DeleteConfirmModal.tsx
> +  }
修正しました。 ありがとうございます！

2024-03-28 12:37 UTC, Fumi369 commented on frontend/components/admin/atoms/DeleteConfirmModal.tsx
> +  onClose: () => void
こちらも修正しました！
カスタム hook のコードを削除したことで、`id` と `deleteTarget` が不要になったので、props は以下のようになりました。
```
  isOpen,
  onClose,
  onClick,
}: {
  isOpen: boolean
  onClose: () => void
  onClick: () => void
  ```

2024-03-28 12:40 UTC, Fumi369 commented on frontend/components/admin/atoms/DeleteConfirmModal.tsx
> +          <Button variant="ghost" onClick={onClose}>
こちらも修正しました！
Suggested change は「いいえ」ボタンになっていますが、「はい」ボタンを意図されていたという思いますので、「はい」ボタンの `onClick`を以下のように修正しました。
```
<Button colorScheme="red" mr={3} onClick={onClick}>
    はい
```

2024-03-28 23:17 UTC, issiyda approved these changes
LGTMです！

2024-03-28 23:57 UTC, merged