BE 学習にかかった時間を保存できるAPIの作成
ishida-frontend/engineer-tenshoku-master pull request #278
Opened 2024-04-01 07:27 UTC by preticure

## 概要

## 実装理由・変更理由

## 特にレビューしてもらいたいこと

## 機能実行結果の動画

## 機能実行結果のスクショ

## UI変更前後のスクショ

## コメント

2024-04-01 07:31 UTC, preticure commented on backend/application/learningRecord.ts
> +      const learningRecord = await prisma.learningRecord.create({
@issiyda 
エラー箇所
`prisma.learningRecord.create()`

エラー文

> プロパティ 'learningRecord' は型 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: { $allModels: { softDelete: () => (id: string) => Promise<void>; }; user: { softDelete: () => (id: string) => Promise<void>; }; ... 10 more ...; advertisement: { ...; }; }; query: {}; client: {}; }>, TypeMapCb, { ...; }>' に存在しません。ts(2339)
> any

![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/fba9d254-6e9b-458c-ac6c-5179b4dc0253)

2024-04-01 07:38 UTC, preticure commented on backend/application/learningRecord.ts
> +      const learningRecord = await prisma.learningRecord.create({
@issiyda 
**やったこと**
テーブル作成時に問題がないか確認→マイグレーションからやり直しましたが、エラー消えず。
PrismaClient周りのエラーなので、マイグレーションか、呼び出し方に問題があると考えたのですが
どこを直したらいいのかわかりませんでした。

2024-04-01 20:25 UTC, preticure commented on backend/controllers/LearningRecordController.ts
> +      const data = await this.learningRecordApplicationService.createLearningRecord(learningRecord)
@issiyda 
バックエンドでlearningRecordApplicationServiceがundefinedというエラー
![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/931a5108-3b03-4a34-b2fe-2cb69d70d61f)

learningRecord.tsファイル19行目で起きてるエラーと関係ある
> プロパティ 'learningRecord' は型 'PrismaClient<PrismaClientOptions, never, DefaultArgs>' に存在しません。ts(2339)
![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/76bb2e7f-ddd2-4359-9a54-c007634c941b)


**考えられる原因**
- LearningRecordApplicationServiceクラス内でPrismaClientを正しくインスタンス化できていない？
- LearningRecordControllerクラスのインスタンスが作成されておらず、そのためlearningRecordApplicationServiceプロパティがundefinedになっている？
→これはLearningRecordController内でメソッド追っていくとlearningRecordApplicationServiceクラスに飛べるので違う気がする
- LearningRecordApplicationServiceクラス内でPrismaを初期化する際の問題に起因する可能性（chatgdp）
→他の実装でそれらしいことしてない気がするけど、分からない

まずlearningRecordApplicationServiceとLearningRecordControllerがそれぞれ何をしているのかもよく分かってないです。

2024-04-01 20:43 UTC, preticure commented on backend/application/learningRecord.ts
> +      const learningRecord = await prisma.learningRecord.create({
@issiyda 
エラー
![image](https://github.com/ishida-frontend/engineer-tenshoku-master/assets/151464878/b8e43e3a-457b-4663-bde1-e2fb117e84c8)

2024-04-03 01:53 UTC, issiyda reviewed
@preticure 
フロントの実装と一緒で良いので分けてPR出してるもの一緒にしてもう一度PR出して下さい。
指摘箇所も修正した上で！
→migrationに関しては一旦このままで大丈夫です。

2024-04-03 01:53 UTC, issiyda commented on frontend/components/organisms/LearningRecord.tsx
> +  }
この部分は親から渡しましょう。

2024-04-03 01:53 UTC, issiyda commented on frontend/components/organisms/LearningRecord.tsx
> +  const [learningRecord, setLearningRecord] = useState<string>()
これはひとまとまりのstateにしたいです。
const [learningRecord, setLearningRecord] = 
time memo ...
などが入ってくる的な。

今は3件なので大丈夫ですが10件とかなってくるとかなり辛いので。

2024-04-03 01:53 UTC, issiyda commented on backend/prisma/migrations/20240401064600_add_learning_record_table/migration.sql
> +    `memo` VARCHAR(191) NULL,
今後ですが基本的にschemaを変更する際は
別のmigrationファイル作成して下さい。

今はdevelopブランチまでしか行っていないので本番適用されていないからいいんですが仮に本番適用されていた場合このファイルを変更しても変更が加わらないので。

2024-04-04 11:16 UTC, preticure commented on frontend/components/organisms/LearningRecord.tsx
> +            <Button onClick={(event) => submitLearningRecord(event)} colorScheme="green">
@issiyda 
submitLearningRecord を呼び出すときに、イベントオブジェクトを渡すように修正

2024-04-04 11:27 UTC, preticure commented on frontend/components/pages/CourseDetail.tsx
> +  }, [learningRecord])
@issiyda 
useEffectでlearningTimeが変更されたら更新するように修正
ここでもlearningTimeのログが0になっているから、親と子で参照している値が違う気がするのですが、どう直したらいいのかわかりません。

2024-04-04 11:49 UTC, issiyda requested changes

2024-04-04 11:49 UTC, issiyda commented on frontend/components/pages/CourseDetail.tsx
> +      resetForm()
@preticure 
router.refresh()
じゃだめそうですか？

2024-04-05 00:11 UTC, issiyda reviewed
@preticure 

数点確認してもらえると！
実装に関しては基本OKです！

2024-04-05 00:11 UTC, issiyda commented on frontend/zod/learningTime.ts
> +})
learningRecordにしますかファイル名と関数名も。
一応memoもバリデーションに含めてもらっていいですか？

2024-04-05 00:11 UTC, issiyda commented on frontend/zod/learningTime.ts
> +  learningTime: z.number().min(1),
```suggestion
  learningTime: z.number().min(1),
  memo: null許容のやつってなかったでしたっけ？？ memo.string..option() かな
```

2024-04-05 00:11 UTC, issiyda commented on frontend/zod/index.ts
> +export * from './learningTime'
```suggestion
export * from './learningRecord'
```
にしたい

2024-04-05 00:11 UTC, issiyda commented on frontend/components/pages/CourseDetail.tsx
> +      }
今回は時間でしかエラーが出ないと思うのですが
時間が入力されていないっていうのを条件に持つのって難しそうですか？

learningTimeValidationResult.
この後にhoursが入力されていなかったら
`時間が入力されていません`
hoursの入力結果を元にしたら
`分数が入力されていません`

的な形で。

2024-04-05 00:11 UTC, issiyda commented on frontend/components/pages/CourseDetail.tsx
> +  }
👍

2024-04-05 08:52 UTC, closed without merging